name: EBAC CI

on:
  push:
    branches: [ ci ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configura Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instala dependências
        run: npm install

      - name: Executa Cypress com servidor em background
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
          install: false
          browser: chrome

      - name: Publica relatório no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
